### PR TITLE
Update omt-nav2-files.md

### PR DESCRIPTION
**Pull request by amathot**
adding keyboard shortcut

### CODE REVIEW

**Review by msoutopico — CHANGES_REQUESTED** [review]
You must use lowercase letters, i.e. `++ctrl+l++`. Could you please update your edit?

**Comment by amathot** [comment]
changes implemented

**Review by msoutopico — CHANGES_REQUESTED** [review]
The shortcut should be ++ctrl+l++ (lower case), could you please update it?

**Review by msoutopico — APPROVED** [review]
sorry, hadn't seen this one

**Pull request merged**
